user nginx;
worker_processes auto;
pid /var/run/nginx.pid;

events {
    worker_connections 4096;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" "$http_user_agent"';
    log_format postback_safe '$remote_addr - $remote_user [$time_local] '
                             '"$request_method $uri $server_protocol" '
                             '$status $body_bytes_sent "$http_user_agent"';
    access_log /dev/stdout main;
    error_log /dev/stderr warn;
    sendfile on;
    keepalive_timeout 30s;
    resolver 127.0.0.11 valid=10s ipv6=off;
    include /etc/nginx/conf.d/*.conf;
}
