#!/usr/bin/env bash
# Run with traffic writers stopped. Preserve old tables until verification.
set -Eeuo pipefail
umask 077
container=traffoflex-clickhouse-1
database=traffoflex
production=0
backup_dir=""
restore=0
while (($#)); do
  case "$1" in
    --container) container=$2; shift 2 ;;
    --database) database=$2; shift 2 ;;
    --production) production=1; shift ;;
    --backup-dir) backup_dir=$2; shift 2 ;;
    --restore) restore=1; shift ;;
    --help) printf 'Usage: %s [--production] [--container NAME] [--database NAME] [--backup-dir DIR] [--restore]\nStop traffic writers and take a volume backup before migrating.\n' "$0"; exit 0 ;;
    *) printf 'Unknown argument: %s\n' "$1" >&2; exit 2 ;;
  esac
done
[[ "$container" =~ ^[A-Za-z0-9_.-]+$ && "$database" =~ ^[A-Za-z0-9_]+$ ]]
suffix=""
if [[ "$production" == 1 ]]; then suffix=_local; fi
ch() {
  docker exec -i -e TRAFFOFLEX_MIGRATION_DATABASE="$database" "$container" sh -ec 'exec clickhouse-client --user "$CLICKHOUSE_USER" --password "$CLICKHOUSE_PASSWORD" --database "$TRAFFOFLEX_MIGRATION_DATABASE" "$@"' -- "$@"
}
exists() { [[ "$(ch --query "EXISTS TABLE $database.$1")" == 1 ]]; }
view_select() {
  ch --format TabSeparatedRaw --query "SHOW CREATE TABLE $database.$1" | awk 'BEGIN{found=0} /^AS[[:space:]]*$/{found=1; next} /^AS SELECT/{found=1; sub(/^AS /, "")} found{print}'
}
restore_state() {
  test -f "$backup_dir/state.sh"
  test -f "$backup_dir/schema.changed"
  # This private file was generated by declare -p, contains no credentials,
  # and lives next to the saved SQL definitions from this migration.
  source "$backup_dir/state.sh"
  if exists click_events_queue; then ch --query "DETACH TABLE $database.click_events_queue PERMANENTLY"; fi
  for view in click_events_to_stats_1m click_stats_1m_to_stats_1h click_events_to_stats_1s click_stats_1s_to_stats_1m click_events_to_stats_1h click_stats_1h_to_stats_1d click_attribution_lookup_mv; do
    ch --query "DROP VIEW IF EXISTS $database.$view SYNC"
  done
  for table in "click_stats_1m$suffix" "click_stats_1h$suffix" "click_attribution_lookup$suffix"; do
    saved="${table}_before_hour_day"
    if exists "$saved"; then
      if exists "$table"; then ch --query "RENAME TABLE $database.$table TO $database.${table}_failed_hour_day_$(date +%s)"; fi
      ch --query "RENAME TABLE $database.$saved TO $database.$table"
    fi
  done
  ch --query "DROP TABLE IF EXISTS $database.click_stats_1d$suffix SYNC"
  if [[ "$production" == 1 ]]; then
    for table in click_stats_1h click_stats_1m click_stats_1d click_attribution_lookup; do
      ch --query "DROP TABLE IF EXISTS $database.$table SYNC"
    done
    for table in click_stats_1m click_stats_1h click_attribution_lookup; do
      if [[ -f "$backup_dir/$table.sql" ]]; then ch --multiquery < "$backup_dir/$table.sql"; fi
    done
  fi
  for view in click_events_to_stats_1m click_stats_1m_to_stats_1h click_events_to_stats_1s click_stats_1s_to_stats_1m click_attribution_lookup_mv; do
    if [[ -f "$backup_dir/$view.sql" ]]; then ch --multiquery < "$backup_dir/$view.sql"; fi
  done
  # New clicks may have arrived since the upgrade. Rebuild the old chain from
  # retained raw history rather than restoring stale aggregate snapshots.
  if exists "click_stats_1h$suffix"; then
    differs=$(ch --query "SELECT raw_clicks != old_clicks OR abs(raw_cost-old_cost) > greatest(1e-8,abs(old_cost)*1e-9) FROM (SELECT count() raw_clicks,sum(cost) raw_cost FROM $database.click_events$suffix) AS raw CROSS JOIN (SELECT sum(clicks) old_clicks,sum(cost) old_cost FROM $database.click_stats_1h$suffix) AS hourly")
    if [[ "$differs" == 1 ]]; then
      for table in "click_stats_1h$suffix" "click_stats_1m$suffix" "click_stats_1s$suffix" "click_attribution_lookup$suffix"; do
        if exists "$table"; then ch --query "TRUNCATE TABLE $database.$table SYNC"; fi
      done
      if exists click_events_to_stats_1m; then raw_view=click_events_to_stats_1m; target="click_stats_1m$suffix";
      elif exists click_events_to_stats_1s; then raw_view=click_events_to_stats_1s; target="click_stats_1s$suffix";
      else printf 'No legacy click view available for rollback rebuild\n' >&2; return 1; fi
      sql=$(view_select "$raw_view"); test -n "$sql"
      ch --query "INSERT INTO $database.$target $sql"
      if exists click_attribution_lookup_mv; then
        sql=$(view_select click_attribution_lookup_mv); test -n "$sql"
        ch --query "INSERT INTO $database.click_attribution_lookup$suffix $sql"
      fi
      ch --query "SELECT throwIf(raw_clicks != old_clicks OR abs(raw_cost-old_cost) > greatest(1e-8,abs(old_cost)*1e-9), 'Rollback rebuild verification failed') FROM (SELECT count() raw_clicks,sum(cost) raw_cost FROM $database.click_events$suffix) AS raw CROSS JOIN (SELECT sum(clicks) old_clicks,sum(cost) old_cost FROM $database.click_stats_1h$suffix) AS hourly"
    fi
  fi
  if [[ "$queue_was_active" == 1 ]]; then ch --query "ATTACH TABLE $database.click_events_queue"; fi
  touch "$backup_dir/schema.restored"
  printf 'SCHEMA_RESTORED=%s\n' "$database"
}
if [[ "$restore" == 1 ]]; then restore_state; exit 0; fi

# A successful migration is a no-op on subsequent invocations.
if exists "click_stats_1d$suffix" && ! exists "click_stats_1m$suffix"; then
  test "$(ch --query "SELECT count() FROM system.columns WHERE database = '$database' AND table = 'click_stats_1h$suffix' AND name = 'zone_id'")" = 1
  exists click_events_to_stats_1h
  exists click_stats_1h_to_stats_1d
  printf 'ALREADY_MIGRATED=%s\n' "$database"
  exit 0
fi
if exists "click_stats_1d$suffix"; then printf 'Daily table already exists; inspect the incomplete migration.\n' >&2; exit 1; fi
if [[ -z "$backup_dir" ]]; then backup_dir=$(mktemp -d /tmp/traffoflex-hour-day.XXXXXX); else mkdir -p "$backup_dir"; fi
chmod 700 "$backup_dir"
test ! -e "$backup_dir/state.sh"
queue_was_active=0
if exists click_events_queue; then queue_was_active=1; fi
declare -p container database production suffix queue_was_active > "$backup_dir/state.sh"
for view in click_events_to_stats_1m click_stats_1m_to_stats_1h click_events_to_stats_1s click_stats_1s_to_stats_1m click_attribution_lookup_mv; do
  if exists "$view"; then ch --format TabSeparatedRaw --query "SHOW CREATE TABLE $database.$view" > "$backup_dir/$view.sql"; fi
done
if [[ "$production" == 1 ]]; then
  for table in click_stats_1m click_stats_1h click_attribution_lookup; do
    if exists "$table"; then ch --format TabSeparatedRaw --query "SHOW CREATE TABLE $database.$table" > "$backup_dir/$table.sql"; fi
  done
fi
phase=paused
on_error() {
  code=$?
  trap - ERR
  if [[ "$phase" == changed ]]; then
    printf 'Migration failed; restoring saved tables and views.\n' >&2
    if ! bash "$0" --restore --backup-dir "$backup_dir"; then printf 'Schema restore failed; keep writers stopped and inspect %s\n' "$backup_dir" >&2; fi
  elif [[ "$queue_was_active" == 1 ]]; then
    if ! exists click_events_queue; then ch --query "ATTACH TABLE $database.click_events_queue" || printf 'Could not reattach click ingestion.\n' >&2; fi
  fi
  exit "$code"
}
trap on_error ERR
if [[ "$queue_was_active" == 1 ]]; then ch --query "DETACH TABLE $database.click_events_queue PERMANENTLY"; fi
# Raw history is needed to reconstruct GEO/device/placement dimensions. Refuse
# to replace historical aggregates when the raw click history is incomplete.
if exists "click_stats_1h$suffix"; then
  ch --query "SELECT throwIf(raw_clicks != old_clicks OR abs(raw_cost - old_cost) > greatest(1e-8, abs(old_cost)*1e-9), 'Raw history does not match hourly totals; preserve old tables and plan a bounded historical migration') FROM (SELECT count() AS raw_clicks, sum(cost) AS raw_cost FROM $database.click_events$suffix) AS raw CROSS JOIN (SELECT sum(clicks) AS old_clicks, sum(cost) AS old_cost FROM $database.click_stats_1h$suffix) AS hourly"
fi
phase=changed
touch "$backup_dir/schema.changed"
for view in click_events_to_stats_1m click_stats_1m_to_stats_1h click_events_to_stats_1s click_stats_1s_to_stats_1m click_attribution_lookup_mv; do
  ch --query "DROP VIEW IF EXISTS $database.$view SYNC"
done
for table in "click_stats_1m$suffix" "click_stats_1h$suffix" "click_attribution_lookup$suffix"; do
  if exists "$table"; then ch --query "RENAME TABLE $database.$table TO $database.${table}_before_hour_day"; fi
done
if [[ "$production" == 1 ]]; then
  for table in click_stats_1m click_stats_1h click_attribution_lookup; do ch --query "DROP TABLE IF EXISTS $database.$table SYNC"; done
fi
repo_root=$(cd -- "$(dirname -- "$0")/.." && pwd)
schema_dir="$repo_root/deploy/clickhouse/init"
work="$backup_dir/new-schema"
mkdir -p "$work"
if [[ "$production" == 1 ]]; then
  SCHEMA_SOURCE_DIR="$schema_dir" SCHEMA_TARGET_DIR="$work" sh "$repo_root/deploy/clickhouse/prod/render-schema.sh"
else
  cp "$schema_dir/005_click_attribution.sql" "$work/005_click_attribution.sql"
  cp "$schema_dir/006_click_rollups.sql" "$work/006_click_rollups.sql"
fi
awk '/^CREATE TABLE IF NOT EXISTS traffoflex.attributed_conversion_events/{exit} {print}' "$work/005_click_attribution.sql" | sed "s/traffoflex\\./$database./g" > "$work/lookup.sql"
sed "s/traffoflex\\./$database./g" "$work/006_click_rollups.sql" > "$work/rollups.sql"
ch --multiquery < "$work/lookup.sql"
ch --multiquery < "$work/rollups.sql"
if [[ "$production" == 1 ]]; then
  sed "s/traffoflex\\./$database./g; s/'traffoflex'/'$database'/g" "$work/007_distributed_tables.sql" > "$work/facades.sql"
  ch --multiquery < "$work/facades.sql"
fi
# Reuse the view SELECTs so historical and live click normalization match.
for pair in "click_attribution_lookup_mv:click_attribution_lookup$suffix" "click_events_to_stats_1h:click_stats_1h$suffix"; do
  view=${pair%%:*}; target=${pair#*:}
  ch --format TabSeparatedRaw --query "SHOW CREATE TABLE $database.$view" > "$work/$view.ddl"
  # The AS SELECT delimiter is part of ClickHouse's normalized SHOW CREATE SQL.
  sql=$(view_select "$view")
  test -n "$sql"
  ch --query "INSERT INTO $database.$target $sql"
done
ch --query "SELECT throwIf(raw_clicks != hourly_clicks OR hourly_clicks != daily_clicks OR abs(raw_cost - hourly_cost) > greatest(1e-8, abs(raw_cost)*1e-9) OR abs(hourly_cost - daily_cost) > greatest(1e-8, abs(raw_cost)*1e-9), 'Hour/day backfill verification failed') FROM (SELECT count() AS raw_clicks, sum(cost) AS raw_cost FROM $database.click_events$suffix) AS raw CROSS JOIN (SELECT sum(clicks) AS hourly_clicks, sum(cost) AS hourly_cost FROM $database.click_stats_1h$suffix) AS hourly CROSS JOIN (SELECT sum(clicks) AS daily_clicks, sum(cost) AS daily_cost FROM $database.click_stats_1d$suffix) AS daily"
if [[ "$queue_was_active" == 1 ]]; then ch --query "ATTACH TABLE $database.click_events_queue"; fi
trap - ERR
touch "$backup_dir/migration.completed"
printf 'MIGRATED=%s\nSCHEMA_BACKUP=%s\n' "$database" "$backup_dir"
printf 'Keep writers stopped until the new API is installed. Saved *_before_hour_day tables can be dropped after successful verification.\n'
